apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticket-335609
  artifacts:
    # - image: razmjo/auth
    - image: us.gcr.io/ticket-335609/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    