apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  # - image: us.gcr.io/microservices-335612/auth
  - image: razmjo/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
  - image: razmjo/ticketing-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/.js'
          dest: .
deploy:
  kubectl:
    manifests:
    - ./k8s/*
