apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: us.gcr.io/microservices-335612/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
    - k8s/auth-depl.yaml
    - k8s/ingress-service.yaml
