apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ticket-mongo-depl
  namespace: default
  labels:
    app:  ticket-mongo
spec:
  selector:
    matchLabels:
      app: ticket-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app:  ticket-mongo
    spec:
      containers:
      - name:  ticket-mongo
        image:  mongo:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-mongo-service
  namespace: default
spec:
  selector:
    app: ticket-mongo
  type: ClusterIP
  ports:
  - name: ticket-mongo
    protocol: TCP
    port:  27017
    targetPort: 27017